# Generated by Django 5.0.6 on 2025-06-26 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brainspaces", "0001_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrainCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField(blank=True)),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("youtube", "youtube"),
                            ("tweet", "tweet"),
                            ("spotify", "spotify"),
                            ("link", "link"),
                            ("text", "text"),
                        ],
                        default="link",
                    ),
                ),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("vectoredOnData", models.TextField(blank=True)),
                (
                    "brain_space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brain_cards",
                        to="brainspaces.brainspace",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="tags.tag")),
            ],
        ),
    ]
